"use client";

import { FormEvent, useState } from "react";
import type { BookDraft } from "@/lib/types";

export default function SearchBooksPage() {
  const [query,setQuery]=useState(""),[books,setBooks]=useState<BookDraft[]>([]),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState(""),[added,setAdded]=useState<string[]>([]);
  const keyFor=(book:BookDraft)=>book.open_library_id||book.isbn||`${book.title}-${book.author}`;
  async function search(event:FormEvent){event.preventDefault();if(query.trim().length<2)return;setLoading(true);setError("");setSearched(false);try{const response=await fetch(`/api/search-books?q=${encodeURIComponent(query.trim())}`);const data=await response.json();if(!response.ok)throw new Error(data.error||"Search failed");setBooks(data.books||[]);setSearched(true)}catch(e){setError(e instanceof Error?e.message:"Search failed")}finally{setLoading(false)}}
  async function add(book:BookDraft){const key=keyFor(book);setToast("Saving to your library…");try{const response=await fetch("/api/books",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({books:[book]})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save book");if(data.skipped){setToast("That book is already in your library");return}setAdded(v=>[...v,key]);setToast("Added to your library")}catch(e){setToast(e instanceof Error?e.message:"Could not save book")}finally{setTimeout(()=>setToast(""),2400)}}
  return <section className="shell discover-shell"><div className="discover-head"><div><p className="eyebrow">Free catalogue search</p><h1>Find your next book</h1><p className="lede">Search millions of books by title, author, or ISBN—no AI credits needed.</p></div><span className="openlibrary-badge">Powered by Open Library</span></div>
    <form className="catalog-search" onSubmit={search}><label className="field-shell"><span aria-hidden="true">⌕</span><input aria-label="Search Open Library" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try a title, author, or ISBN…" /></label><button className="primary" disabled={loading||query.trim().length<2}>{loading?"Searching…":"Search books"}</button></form>
    {error&&<div className="empty compact"><h2>Search unavailable</h2><p>{error}</p></div>}
    {!error&&searched&&books.length===0&&<div className="empty compact"><h2>No books found</h2><p>Try fewer words, another spelling, or an ISBN.</p></div>}
    <div className="search-results">{books.map(book=>{const key=keyFor(book),isAdded=added.includes(key);return <article className="result-card" key={key}><div className="result-cover">{book.cover_image_url?<img src={book.cover_image_url} alt={`Cover of ${book.title}`}/>:<span>⌁</span>}</div><div className="result-info"><span className="result-year">{book.published_date||book.language?.toUpperCase()||"Book"}</span><h2>{book.title}</h2><p className="author">by {book.author}</p>{book.publisher&&<p className="result-publisher">{book.publisher}</p>}<div className="result-facts">{book.page_count&&<span>{book.page_count} pages</span>}{book.average_rating&&<span>★ {book.average_rating.toFixed(1)}</span>}</div><div className="result-actions"><button className="primary" disabled={isAdded} onClick={()=>add(book)}>{isAdded?"Added ✓":"Add to library"}</button>{book.preview_url&&<a href={book.preview_url} target="_blank" rel="noopener noreferrer">Details ↗</a>}</div></div></article>})}</div>
    {toast&&<div className="toast" role="status">{toast}</div>}
  </section>;
}
