"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { saveLocalBooks } from "@/lib/local-books";
import { BOOK_STATUSES, BOOK_STATUS_LABELS, type BookDraft, type BookStatus } from "@/lib/types";

export default function ReviewPage(){const router=useRouter();const [books,setBooks]=useState<BookDraft[]>([]),[ready,setReady]=useState(false),[errors,setErrors]=useState<number[]>([]),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
  useEffect(()=>{try{const detected=JSON.parse(sessionStorage.getItem("detected-books")||"[]");setBooks(detected.map((book:BookDraft)=>({...book,status:book.status||"wishlist"})))}finally{setReady(true)}},[]);
  function update(i:number,key:keyof BookDraft,value:string){setBooks(v=>v.map((b,n)=>n===i?{...b,[key]:value}:b));setErrors(v=>v.filter(n=>n!==i))}
  async function save(){const invalid=books.map((b,i)=>b.title.trim()?null:i).filter((i):i is number=>i!==null);if(invalid.length){setErrors(invalid);return}setSaving(true);setSaveError("");try{const response=await fetch("/api/books",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({books})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Could not save books");if(data.storage==="supabase"){sessionStorage.removeItem("detected-books");router.push(`/?saved=${data.books?.length||0}&skipped=${data.skipped||0}`);return}const result=saveLocalBooks(books);sessionStorage.removeItem("detected-books");router.push(`/?saved=${result.added.length}&skipped=${result.skipped.length}`)}catch(error){setSaveError(error instanceof Error?error.message:"Could not save books. Your review has been kept.")}finally{setSaving(false)}}
  if(!ready)return null;
  return <section className="shell review-shell"><div className="review-top"><div><p className="eyebrow">Almost there</p><h1>Review your books</h1><p className="lede">We found {books.length} {books.length===1?"book":"books"}. Give the details a quick look before saving.</p></div></div>
    {books.length===0?<div className="empty"><h2>No books to review</h2><p>Head back and scan a photo first.</p><button className="primary" onClick={()=>router.push("/scan")}>Scan books</button></div>:<><div className="detected-list">{books.map((book,i)=><article className="detected" key={i}><div className="detected-head"><span className="confidence">{Math.round((book.confidence_score||0)*100)}% match</span><button className="icon-btn" aria-label={`Remove ${book.title||"book"}`} onClick={()=>setBooks(v=>v.filter((_,n)=>n!==i))}>Remove ✕</button></div>{(book.cover_image_url||book.description)&&<div className="metadata-preview">{book.cover_image_url&&<img src={book.cover_image_url} alt=""/>}<div><strong>{book.metadata_source==="google_books"?"Matched with Google Books":"Matched with Open Library"}</strong>{book.description&&<p>{book.description}</p>}{(book.publisher||book.published_date)&&<small>{[book.publisher,book.published_date].filter(Boolean).join(" · ")}</small>}</div></div>}<div className="form-grid"><label>Title *<input className={errors.includes(i)?"error-input":""} value={book.title} onChange={e=>update(i,"title",e.target.value)}/>{errors.includes(i)&&<span className="error-text">A title is required</span>}</label><label>Author<input value={book.author} onChange={e=>update(i,"author",e.target.value)}/></label><label>ISBN<input inputMode="numeric" value={book.isbn||""} onChange={e=>update(i,"isbn",e.target.value)}/></label><label>Genre<input value={book.genre||""} onChange={e=>update(i,"genre",e.target.value)}/></label><label>Collection status<select value={book.status||"wishlist"} onChange={e=>update(i,"status",e.target.value as BookStatus)}>{BOOK_STATUSES.map(status=><option value={status} key={status}>{BOOK_STATUS_LABELS[status]}</option>)}</select></label></div></article>)}</div>{saveError&&<p className="form-error save-error" role="alert">{saveError}</p>}<div className="review-actions"><p>{books.length} selected · You can edit these later</p><button className="primary" disabled={saving||!books.length} onClick={save}>{saving?"Saving…":`Save ${books.length} ${books.length===1?"book":"books"}`}</button></div></>}
  </section>}
